// @ts-check
window.SITE_DATA_BLOGS = {
    blogs_intro: "Here are some of my recent talks, session presentations, and blog posts, which reflect my interests in machine learning, AI research, and software development. I enjoy sharing my insights and experiences through writing and speaking, and I hope these posts provide value to others in the field. If you have any questions or want to discuss any of these topics further, please feel free to reach out.",
    blogs: [
        {
            title: "SOLID",
            summary: "Session slides on SOLID principles for maintainable object-oriented design.",
            link: "../resources/docs/talks/SOLID.pdf",
            date: "May 6, 2019",
            tags: ["Design", "OOP", "Architecture"],
            timeToRead: "75 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Flash Cards",
            summary: "Presentation deck used for quick concept reviews and knowledge sharing sessions.",
            link: "../resources/docs/talks/Flash-Cards.pdf",
            date: "March 31, 2024",
            tags: ["Learning", "Workshop"],
            timeToRead: "9 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Meeting Talk",
            file_type: "pptx",
            mode: "Online",
            location: "iSpeak"
        },
        {
            title: "Statistics",
            summary: "Talk slides covering practical statistics concepts for engineering and analysis.",
            link: "../resources/docs/talks/Statistics.pdf",
            date: "April 4, 2024",
            tags: ["Statistics", "Data"],
            timeToRead: "42 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Arden Software"
        },
        {
            title: "Cimex Importer",
            summary: "Technical session deck discussing importer design and integration details.",
            link: "../resources/docs/talks/Cimex_Importer.pdf",
            date: "March 17, 2024",
            tags: ["CAD", "Import", "Engineering"],
            timeToRead: "18 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        },
        {
            title: "Viewport React Component",
            summary: "Presentation on building and structuring viewport-driven UI components.",
            link: "../resources/docs/talks/ViewportReactComponent.pdf",
            date: "September 24, 2025",
            tags: ["React", "Frontend", "UI"],
            timeToRead: "9 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        },
        {
            title: "Lens 2D Render Engine",
            summary: "Talk material explaining architecture and rendering flow for a 2D engine.",
            link: "../resources/docs/talks/Lens%202D%20Render%20Engine.pdf",
            date: "April 25, 2024",
            tags: ["Graphics", "Rendering", "C++"],
            timeToRead: "21 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        },
        {
            title: "Design Pattern: Decorative And Composite",
            summary: "Slides focused on Decorator and Composite patterns with practical examples.",
            link: "../resources/docs/talks/Design%20Pattern_%20DecorativeAndComposite.pdf",
            date: "May 7, 2019",
            tags: ["Design Patterns", "Software Design"],
            timeToRead: "12 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Basics of Computer Graphics and Its Importance",
            summary: "Introductory presentation covering graphics fundamentals and real-world relevance.",
            link: "../resources/docs/talks/Basics%20of%20Computer%20Grapics%20and%20Its%20Importance.pdf",
            date: "April 4, 2019",
            tags: ["Computer Graphics", "Fundamentals"],
            timeToRead: "31 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Talk about Dimension Unit",
            summary: "Session notes and slides on dimension/unit handling in design workflows.",
            link: "../resources/docs/talks/ON-TalkaboutDimensionUnit-070219-0452.pdf",
            date: "May 6, 2019",
            tags: ["CAD", "Dimensions", "Units"],
            timeToRead: "4 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pdf",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Philosophy behind OdRxObject",
            summary: "Technical presentation discussing architecture decisions around OdRxObject.",
            link: "../resources/docs/talks/Philosophy%20behind%20OdRxObject.pptx.pdf",
            date: "December 27, 2018",
            tags: ["CAD", "Architecture", "C++"],
            timeToRead: "36 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Let's Discover Coding in Life",
            summary: "Community-style talk encouraging coding through everyday problem solving.",
            link: "../resources/docs/talks/Let%E2%80%99s%20discover%20coding%20in%20life.pdf",
            date: "December 10, 2023",
            tags: ["Coding", "Community", "Learning"],
            timeToRead: "15 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        }
    ]
};
