// @ts-check
window.SITE_DATA_BLOGS = {
    blogs_intro: "Slides and sessions from talks I've given at Arden Software, Gräbert GmbH, and community events — plus written deep-dives from the RL series.",
    blogs: [
        {
            title: "Finite Markov Decision Processes",
            summary: "Chapter 3 of the RL series: where RL becomes a true framework for sequential decision-making. Covers states, state transitions, the Markov property, returns, value functions, and the Bellman equations.",
            link: "blog-viewer.html?file=../pages/blogs/series/rl/%5B03%5D%20Finite%20Markov%20Decision%20Process.md&title=Finite%20Markov%20Decision%20Processes&author=Dheeraj%20Karki&event=RL%20Series",
            date: "June 1, 2026",
            tags: ["Reinforcement Learning", "MDP", "Series"],
            timeToRead: "30 min read",
            featured: true,
            author: "Dheeraj Karki",
            status: "Published",
            type: "blog",
            file_type: "md",
            event: "RL Series",
            mode: "Online",
            location: "karkid.github.io"
        },
        {
            title: "Multi-Armed Bandits",
            summary: "Chapter 2 of the RL series: the exploration–exploitation tradeoff in its purest form. Covers action-value estimation, epsilon-greedy, UCB, and gradient bandit algorithms.",
            link: "blog-viewer.html?file=../pages/blogs/series/rl/%5B02%5D%20Multi-Armed%20Bandits.md&title=Multi-Armed%20Bandits&author=Dheeraj%20Karki&event=RL%20Series",
            date: "May 20, 2026",
            tags: ["Reinforcement Learning", "Bandits", "Series"],
            timeToRead: "40 min read",
            featured: true,
            author: "Dheeraj Karki",
            status: "Published",
            type: "blog",
            file_type: "md",
            event: "RL Series",
            mode: "Online",
            location: "karkid.github.io"
        },
        {
            title: "What Reinforcement Learning Really Is",
            summary: "Chapter 1 of the RL series: why RL differs from supervised learning, the agent–environment interface, rewards, returns, value functions, and the Bellman equation from first principles.",
            link: "blog-viewer.html?file=../pages/blogs/series/rl/%5B01%5D%20What%20Reinforcement%20Learning%20Is.md&title=What%20Reinforcement%20Learning%20Really%20Is&author=Dheeraj%20Karki&event=RL%20Series",
            date: "May 10, 2026",
            tags: ["Reinforcement Learning", "ML", "Series"],
            timeToRead: "28 min read",
            featured: true,
            author: "Dheeraj Karki",
            status: "Published",
            type: "blog",
            file_type: "md",
            event: "RL Series",
            mode: "Online",
            location: "karkid.github.io"
        },
        {
            title: "SOLID",
            summary: "Session slides on SOLID principles for maintainable object-oriented design.",
            link: "../resources/docs/talks/SOLID.pdf",
            date: "May 6, 2019",
            tags: ["Design", "OOP", "Architecture"],
            timeToRead: "75 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Flash Cards",
            summary: "Presentation deck used for quick concept reviews and knowledge sharing sessions.",
            link: "../resources/docs/talks/Flash-Cards.pdf",
            date: "March 31, 2024",
            tags: ["Learning", "Workshop"],
            timeToRead: "9 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Meeting Talk",
            file_type: "pptx",
            mode: "Online",
            location: "iSpeak"
        },
        {
            title: "Statistics",
            summary: "Talk slides covering practical statistics concepts for engineering and analysis.",
            link: "../resources/docs/talks/Statistics.pdf",
            date: "April 4, 2024",
            tags: ["Statistics", "Data"],
            timeToRead: "42 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Arden Software"
        },
        {
            title: "Cimex Importer",
            summary: "Technical session deck discussing importer design and integration details.",
            link: "../resources/docs/talks/Cimex_Importer.pdf",
            date: "March 17, 2024",
            tags: ["CAD", "Import", "Engineering"],
            timeToRead: "18 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        },
        {
            title: "Viewport React Component",
            summary: "Presentation on building and structuring viewport-driven UI components.",
            link: "../resources/docs/talks/ViewportReactComponent.pdf",
            date: "September 24, 2025",
            tags: ["React", "Frontend", "UI"],
            timeToRead: "9 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        },
        {
            title: "Lens 2D Render Engine",
            summary: "Talk material explaining architecture and rendering flow for a 2D engine.",
            link: "../resources/docs/talks/Lens%202D%20Render%20Engine.pdf",
            date: "April 25, 2024",
            tags: ["Graphics", "Rendering", "C++"],
            timeToRead: "21 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        },
        {
            title: "Design Pattern: Decorative And Composite",
            summary: "Slides focused on Decorator and Composite patterns with practical examples.",
            link: "../resources/docs/talks/Design%20Pattern_%20DecorativeAndComposite.pdf",
            date: "May 7, 2019",
            tags: ["Design Patterns", "Software Design"],
            timeToRead: "12 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Basics of Computer Graphics and Its Importance",
            summary: "Introductory presentation covering graphics fundamentals and real-world relevance.",
            link: "../resources/docs/talks/Basics%20of%20Computer%20Grapics%20and%20Its%20Importance.pdf",
            date: "April 4, 2019",
            tags: ["Computer Graphics", "Fundamentals"],
            timeToRead: "31 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Talk about Dimension Unit",
            summary: "Session notes and slides on dimension/unit handling in design workflows.",
            link: "../resources/docs/talks/ON-TalkaboutDimensionUnit-070219-0452.pdf",
            date: "May 6, 2019",
            tags: ["CAD", "Dimensions", "Units"],
            timeToRead: "4 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pdf",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Philosophy behind OdRxObject",
            summary: "Technical presentation discussing architecture decisions around OdRxObject.",
            link: "../resources/docs/talks/Philosophy%20behind%20OdRxObject.pptx.pdf",
            date: "December 27, 2018",
            tags: ["CAD", "Architecture", "C++"],
            timeToRead: "36 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "In-Person",
            location: "Gräbert GmbH"
        },
        {
            title: "Let's Discover Coding in Life",
            summary: "Community-style talk encouraging coding through everyday problem solving.",
            link: "../resources/docs/talks/Let%E2%80%99s%20discover%20coding%20in%20life.pdf",
            date: "December 10, 2023",
            tags: ["Coding", "Community", "Learning"],
            timeToRead: "15 min read",
            featured: false,
            author: "Dheeraj Karki",
            status: "Presented",
            type: "talk",
            event: "Session Talk",
            file_type: "pptx",
            mode: "Online",
            location: "Arden Software"
        }
    ]
};
