// @ts-check
window.SITE_DATA_PROJECTS = {
    project_intro: "Here are some of the projects I have worked on, which reflect my interests in software development, machine learning, and research. I am always open to new opportunities and collaborations, so feel free to reach out if you want to discuss any of these projects or potential ideas.",
    projects: [
        {
            title: "Epistemic FactKG",
            description: "A knowledge graph generation and claim validation framework for epistemic fact checking. This project processes structured data from AI2-THOR simulations and AVERITEC datasets to build RDF knowledge graphs and generate verifiable claims with epistemic labels.",
            link: "https://github.com/karkid/epistemic-factkg",
            Repo: "Private",
            owner: "Dheeraj Karki",
            status: "In Progress",
            timeline: "February 2026 - Ongoing",
            technology: "Python",
            domain: "Explainable AI, Knowledge Graphs, Fact Checking",
            tags: ["Research", "Git"],
            pinned: true,
            purpose: "Working on the Research draft to validate the affect of the epistemic lables on the claim validation process. The goal is to contribute to the field of Explainable AI using GNNs, so the machine learning models can provide more transparent and interpretable outputs, especially in the context of fact checking and knowledge graph generation."
        },
        {
            title: "ReML — Rebuilding Machine Learning from Scratch",
            description: "The goal is to deeply understand how these libraries work internally by rebuilding their components step by step, testing them against the real implementations, and documenting the learning process.",
            link: "https://github.com/karkid/ReML",
            status: "In Progress",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "April 2024 - Ongoing",
            technology: "Python",
            tags: ["Exploration", "Git"],
            domain: "Machine Learning, Deep Learning, Library Development",
            pinned: true,
            purpose: "I started this project to gain a deeper understanding of how machine learning libraries like PyTorch and TensorFlow work under the hood. By rebuilding their components from scratch, I aim to learn about the underlying algorithms, data structures, and design patterns that make these libraries efficient and powerful. This project is a great way for me to solidify my knowledge of machine learning concepts and improve my programming skills."
        },
        {
            title: "PDDL Planner",
            description: "A collection of PDDL domains and problem files for experimenting with automated planning and AI planning techniques.",
            link: "https://github.com/karkid/PDDL",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "August 2025 - August 2025",
            technology: "PDDL",
            domain: "Automated Planning, AI Planning",
            tags: ["Exploration", "Git"],
            pinned: true,
            purpose: "I created this project to explore automated planning and AI planning techniques using the Planning Domain Definition Language (PDDL). It was a fun project to work on and I learned a lot about planning algorithms and how to represent planning problems using PDDL."
        },
        {
            title: "CAD in Cloud",
            description: "The idea here is to implement a CAD rendering engine on cloud to support and achieve the functionality of 'Anyplace, Anywhere and Anytime'. We use DXF drawing for this project.",
            link: "https://github.com/karkid/CADInColud",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "July 2018 - September 2026",
            technology: "C++",
            domain: "CAD, Cloud Computing",
            tags: ["Research", "Git"],
            pinned: false,
            purpose: "Build for the Master thesis project, the idea was to implement a CAD rendering engine on cloud to support and achieve the functionality of 'Anyplace, Anywhere and Anytime'. We use DXF drawing for this project. It was a great learning experience for me and I enjoyed building it."
        },
        {
            title: "Shape War",
            description: "It is the game build on Entity Component System paradigm.",
            link: "https://github.com/karkid/Shape_War",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "March 2024 - March 2024",
            technology: "C++",
            domain: "Game Development, C++ Programming",
            tags: ["Exploration", "Git"],
            pinned: false,
            purpose: "I wanted to learn about Entity Component System (ECS) architecture and I thought building a simple game would be a fun way to do that. Shape War is a simple game where players control a shape and try to defeat other shapes by shooting them. It was a great learning experience for me and I enjoyed building it."
        },
        {
            title: "Air BNB exploratory analysis",
            description: "Exploratory data analysis of Air BNB listings in London, UK, using Python and Jupyter Notebook.",
            link: "https://github.com/karkid/exploratory-analysis/",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "June 2023 - July 2023",
            technology: "Python",
            domain: "Data Analysis, Machine Learning",
            tags: ["Exploration", "Git"],
            pinned: false,
            purpose: "Learning ML through exploratory data analysis of Air BNB listings in London, UK, using Python and Jupyter Notebook."
        },
        {
            title: "Frido",
            description: "Frido, a todo app with a focus on simplicity and user experience, built using React and Firebase.",
            link: "https://frido.app/",
            status: "Active",
            Repo: "Private",
            owner: "Dheeraj Karki",
            timeline: "August 2019 - February 2026",
            technology: "React, Firebase",
            domain: "Web Development, Productivity Tools",
            tags: ["Volunteer", "Startup", "Git"],
            pinned: false,
            purpose: "Frido is volunteer project that Madsen and I started in 2019. We wanted to create a simple and intuitive todo app that would help people stay organized and productive. We built it using React for the frontend and Firebase for the backend, and we have been continuously improving it based on user feedback. Frido has been a great learning experience for us and we are proud of the product we have created."
        },
        {
            title: "Carbon",
            description: "Building a rendering engine from scratch in C++ using OpenGL.",
            link: "https://github.com/karkid/Carbon_Old",
            timeline: "July 2019 - September 2019",
            status: "Discontinued",
            Repo: "Public",
            owner: "Dheeraj Karki",
            technology: "C++",
            domain: "Graphics Programming, Rendering Engines",
            tags: ["Exploration", "Git"],
            pinned: false,
            purpose: "I had a great interest in learning how rendering engines work and I wanted to build one from scratch. It was a fun project to work on and I learned a lot about graphics programming and OpenGL."
        },
        {
            title: "Tic-Tac-Toe",
            description: "Tic-Tac-Toe is board gamefor two players, X and O, who take turns marking the spaces in a 3×3 grid. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row wins the game.",
            technology: "C++",
            link: "https://github.com/karkid/Tic-Tac-Toe",
            timeline: "December 2018 - December 2018",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            tags: ["Exploration", "Git"],
            pinned: false,
            domain: "Game Development, C++ Programming",
            purpose: "I had created similar project in my first year of bachelor degree in C. I got chance to recreate it for an interview process in C++. It was a fun project to work and I remember it as Hello World of C++ for me."
        },
        {
            title: "Lens 2D Render Engine",
            description: "Improving the rendering pipeline and architecture of a 2D engine to enhance performance and visual quality.",
            link: "",
            presentation_link: "../resources/docs/talks/Lens%202D%20Render%20Engine.pdf",
            Repo: "Private",
            status: "Completed",
            timeline: "November 2019 - July 2020",
            technology: "JavaScript, WebGL",
            domain: "Graphics, Rendering, JavaScript",
            tags: ["Research", "Office"],
            pinned: true,
            owner: "Arden Software",
            purpose: "Enhancing the 2D rendering engine to improve performance and visual quality for internal projects."
        },
        {
            title: "Cimex Importer",
            description: "Designing and implementing an importer for the Cimex CAD format, including handling geometry, metadata, and integration with existing CAD systems.",
            link: "",
            presentation_link: "../resources/docs/talks/Cimex_Importer.pdf",
            Repo: "Private",
            status: "Completed",
            timeline: "September 2021 - October 2021",
            technology: "C++",
            domain: "CAD, Interoperability, Data Exchange",
            tags: ["Research", "Office"],
            pinned: true,
            owner: "Arden Software",
            purpose: "Reverse engineering the Cimex CAD format to build an importer that can handle geometry, metadata, and integrate with existing CAD systems. This project is important for improving interoperability and data exchange in CAD workflows."
        },
        {
            title: "Viewport React Component",
            summary: "Presentation on building and structuring viewport-driven UI components.",
            link: "",
            presentation_link: "../resources/docs/talks/ViewportReactComponent.pdf",
            Repo: "Private",
            status: "Completed",
            timeline: "November 2025 - November 2025",
            technology: "React, JavaScript, C++",
            domain: "Frontend Development, UI Components",
            tags: ["Research", "Office"],
            pinned: true,
            owner: "Arden Software",
            purpose: "Designing a viewport react component which will be same for native and web. The goal is to have a single component that can be used across different platforms, improving code reuse and consistency in the user interface. This project is important for streamlining development and providing a seamless experience for users across native and web applications."
        }
    ]
};
