// @ts-check
window.SITE_DATA_PROJECTS = {
    project_intro: "Here are some of the projects I have worked on, which reflect my interests in software development, machine learning, and research. I am always open to new opportunities and collaborations, so feel free to reach out if you want to discuss any of these projects or potential ideas.",
    projects: [
        {
            title: "Epistemic FactKG",
            description: "A trust-isolating fact-verification benchmark exposing a critical flaw in existing datasets: evidence text is byte-identical across high- and low-trust sources, so only the source-trust scalar determines the verdict. A trust-blind model collapses to chance (macro-F1 0.39) while a trust-aware heterogeneous GNN achieves 0.92 ± 0.02 on 2,200 records.",
            link: "https://github.com/karkid/epistemic-factkg",
            Repo: "Public",
            owner: "Dheeraj Karki",
            status: "In Progress",
            timeline: "February 2026 - Ongoing",
            technology: "Python, PyTorch, DGL, Heterogeneous GNN",
            domain: "Benchmark Design, Explainable AI, Knowledge Graphs, NLP",
            tags: ["Research", "Git"],
            pinned: true,
            purpose: "Existing fact-verification benchmarks leak verdicts through writing register — a trust-blind model scores 99.6% accuracy by reading text style alone, never touching source identity. This benchmark isolates source trust as the sole signal. Key finding: even with access to the trust scalar, a linear model scores only 0.20 on mid-tier boundary cases, showing that fact-checking models need to reason over trust continuously rather than learn a simple high/low threshold."
        },
        {
            title: "ReML — Rebuilding Machine Learning from Scratch",
            description: "The goal is to deeply understand how these libraries work internally by rebuilding their components step by step, testing them against the real implementations, and documenting the learning process.",
            link: "https://github.com/karkid/ReML",
            status: "In Progress",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "April 2024 - Ongoing",
            technology: "Python",
            tags: ["Exploration", "Git"],
            domain: "Machine Learning, Deep Learning, Library Development",
            pinned: true,
            purpose: "Rebuilding PyTorch and TensorFlow components from scratch to develop a deep understanding of the algorithms, data structures, and design patterns that make ML libraries efficient."
        },
        {
            title: "PDDL Planner",
            description: "A collection of PDDL domains and problem files for experimenting with automated planning and AI planning techniques.",
            link: "https://github.com/karkid/PDDL",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "August 2025 - August 2025",
            technology: "PDDL",
            domain: "Automated Planning, AI Planning",
            tags: ["Exploration", "Git"],
            pinned: true,
            purpose: "Built to explore automated planning techniques and domain modeling using PDDL as part of my AI coursework."
        },
        {
            title: "CAD in Cloud",
            description: "The idea here is to implement a CAD rendering engine on cloud to support and achieve the functionality of 'Anyplace, Anywhere and Anytime'. We use DXF drawing for this project.",
            link: "https://github.com/karkid/CADInColud",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "July 2018 - January 2019",
            technology: "C++",
            domain: "CAD, Cloud Computing",
            tags: ["Research", "Git"],
            pinned: false,
            purpose: "Master's thesis project: a cloud-hosted CAD rendering engine for DXF drawings, enabling access from any device, anywhere."
        },
        {
            title: "Shape War",
            description: "It is the game build on Entity Component System paradigm.",
            link: "https://github.com/karkid/Shape_War",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "March 2024 - March 2024",
            technology: "C++",
            domain: "Game Development, C++ Programming",
            tags: ["Exploration", "Git"],
            pinned: false,
            purpose: "Built to learn Entity Component System (ECS) architecture through a concrete game project."
        },
        {
            title: "Airbnb Exploratory Analysis",
            description: "Exploratory data analysis of Airbnb listings in London, UK, using Python and Jupyter Notebook.",
            link: "https://github.com/karkid/exploratory-analysis/",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            timeline: "June 2023 - July 2023",
            technology: "Python",
            domain: "Data Analysis, Machine Learning",
            tags: ["Exploration", "Git"],
            pinned: false,
            purpose: "Learning ML fundamentals through exploratory data analysis on real-world Airbnb listings data."
        },
        {
            title: "Frido",
            description: "Frido, a todo app with a focus on simplicity and user experience, built using React and Firebase.",
            link: "https://frido.app/",
            status: "Active",
            Repo: "Private",
            owner: "Dheeraj Karki",
            timeline: "August 2019 - February 2026",
            technology: "React, Firebase",
            domain: "Web Development, Productivity Tools",
            tags: ["Volunteer", "Startup", "Git"],
            pinned: false,
            purpose: "Co-founded with Madsen in 2019 as a volunteer project to build a clean, intuitive todo app. I contributed to the product until February 2026; the project continues independently."
        },
        {
            title: "Carbon",
            description: "Building a rendering engine from scratch in C++ using OpenGL.",
            link: "https://github.com/karkid/Carbon_Old",
            timeline: "July 2019 - September 2019",
            status: "Discontinued",
            Repo: "Public",
            owner: "Dheeraj Karki",
            technology: "C++",
            domain: "Graphics Programming, Rendering Engines",
            tags: ["Exploration", "Git"],
            pinned: false,
            purpose: "Built to learn graphics programming and OpenGL internals from the ground up."
        },
        {
            title: "Tic-Tac-Toe",
            description: "Tic-Tac-Toe is board game for two players, X and O, who take turns marking the spaces in a 3×3 grid. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row wins the game.",
            technology: "C++",
            link: "https://github.com/karkid/Tic-Tac-Toe",
            timeline: "December 2018 - December 2018",
            status: "Completed",
            Repo: "Public",
            owner: "Dheeraj Karki",
            tags: ["Exploration", "Git"],
            pinned: false,
            domain: "Game Development, C++ Programming",
            purpose: "Recreated a C project from my bachelor's degree in C++ as part of an interview process — my equivalent of a C++ 'Hello World'."
        },
        {
            title: "Lens 2D Render Engine",
            description: "Improving the rendering pipeline and architecture of a 2D engine to enhance performance and visual quality.",
            link: "",
            presentation_link: "../resources/docs/talks/Lens%202D%20Render%20Engine.pdf",
            Repo: "Private",
            status: "Completed",
            timeline: "November 2019 - July 2020",
            technology: "JavaScript, WebGL",
            domain: "Graphics, Rendering, JavaScript",
            tags: ["Research", "Office"],
            pinned: true,
            owner: "Arden Software",
            purpose: "Redesigned the 2D rendering pipeline at Arden Software to improve performance and visual quality for CAD workflows."
        },
        {
            title: "Cimex Importer",
            description: "Designing and implementing an importer for the Cimex CAD format, including handling geometry, metadata, and integration with existing CAD systems.",
            link: "",
            presentation_link: "../resources/docs/talks/Cimex_Importer.pdf",
            Repo: "Private",
            status: "Completed",
            timeline: "September 2021 - October 2021",
            technology: "C++",
            domain: "CAD, Interoperability, Data Exchange",
            tags: ["Research", "Office"],
            pinned: true,
            owner: "Arden Software",
            purpose: "Reverse-engineered the Cimex CAD format to build an importer that handles geometry, metadata, and integrates with existing CAD systems."
        },
        {
            title: "Viewport React Component",
            description: "Designing and implementing a cross-platform viewport component shared between native and web product surfaces.",
            link: "",
            presentation_link: "../resources/docs/talks/ViewportReactComponent.pdf",
            Repo: "Private",
            status: "Completed",
            timeline: "November 2025 - November 2025",
            technology: "React, JavaScript, C++",
            domain: "Frontend Development, UI Components",
            tags: ["Research", "Office"],
            pinned: true,
            owner: "Arden Software",
            purpose: "Designed a single viewport React component for both native and web surfaces to improve code reuse and UI consistency across product workflows."
        }
    ]
};
